import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = dirname(dirname(dirname(fileURLToPath(import.meta.url))))
const lockDirectory = join(repoRoot, '.tmp', 'version-sync.lock')
const lockTimeoutMs = 30000
const staleLockMs = 60000
let writeCounter = 0
const shouldUseNextCommitBuildNumber = process.argv.includes('--next-commit')

await acquireLock()
try {
  syncVersion()
} finally {
  rmSync(lockDirectory, { recursive: true, force: true })
}

function syncVersion() {
  const versionInfo = readVersionInfo()
  const { version } = versionInfo
  validateSemverLikeVersion(version, 'VERSION')

  const packageJsonPaths = [
    'package.json',
    'apps/desktop/package.json',
    'apps/sheet-corrector/package.json',
    'apps/web/package.json',
    'packages/adapters/package.json',
    'packages/core/package.json',
    'packages/ui/package.json',
    'packages/xdts/package.json',
    'tools/csv-xdts-compare/package.json',
    'tools/xdts-inspect/package.json',
    'tools/xdts-patch/package.json',
  ]

  const packageLockPackageKeys = [
    '',
    'apps/desktop',
    'apps/sheet-corrector',
    'apps/web',
    'packages/adapters',
    'packages/core',
    'packages/ui',
    'packages/xdts',
    'tools/csv-xdts-compare',
    'tools/xdts-inspect',
    'tools/xdts-patch',
  ]

  for (const packageJsonPath of packageJsonPaths) {
    const packageJson = readJson(packageJsonPath)
    packageJson.version = version
    writeJson(packageJsonPath, packageJson)
  }

  const packageLock = readJson('package-lock.json')
  packageLock.version = version
  for (const key of packageLockPackageKeys) {
    if (packageLock.packages?.[key]) {
      packageLock.packages[key].version = version
    }
  }
  writeJson('package-lock.json', packageLock)

  const tauriConfig = readJson('apps/desktop/src-tauri/tauri.conf.json')
  tauriConfig.version = version
  writeJson('apps/desktop/src-tauri/tauri.conf.json', tauriConfig)

  const sheetCorrectorTauriConfig = readJson('apps/sheet-corrector/src-tauri/tauri.conf.json')
  sheetCorrectorTauriConfig.version = version
  writeJson('apps/sheet-corrector/src-tauri/tauri.conf.json', sheetCorrectorTauriConfig)

  const cargoTomlPath = 'apps/desktop/src-tauri/Cargo.toml'
  writeText(
    cargoTomlPath,
    updateTomlPackageVersion(readFileSync(join(repoRoot, cargoTomlPath), 'utf8'), version),
  )

  const sheetCorrectorCargoTomlPath = 'apps/sheet-corrector/src-tauri/Cargo.toml'
  writeText(
    sheetCorrectorCargoTomlPath,
    updateTomlPackageVersion(readFileSync(join(repoRoot, sheetCorrectorCargoTomlPath), 'utf8'), version),
  )

  const cargoLockPath = 'apps/desktop/src-tauri/Cargo.lock'
  writeText(
    cargoLockPath,
    updateCargoLockPackageVersion(readFileSync(join(repoRoot, cargoLockPath), 'utf8'), 'xsheet-remap', version),
  )

  const sheetCorrectorCargoLockPath = 'apps/sheet-corrector/src-tauri/Cargo.lock'
  if (existsSync(join(repoRoot, sheetCorrectorCargoLockPath))) {
    writeText(
      sheetCorrectorCargoLockPath,
      updateCargoLockPackageVersion(readFileSync(join(repoRoot, sheetCorrectorCargoLockPath), 'utf8'), 'xsheet-corrector', version),
    )
  }

  writeText(
    'packages/ui/src/appVersion.ts',
    `// Generated by tools/version/sync-version.mjs from VERSION_BASE, BUILD_NUMBER_OFFSET, and the Git commit count.\nexport const APP_VERSION = '${version}'\n`,
  )
  writeText(
    'apps/csp-import-helper/src/csp_import_helper/__init__.py',
    `"""CSP import helper package."""\n\n# Generated by tools/version/sync-version.mjs from VERSION_BASE, BUILD_NUMBER_OFFSET, and the Git commit count.\n__version__ = "${version}"\n`,
  )
  if (versionInfo.buildNumber !== null) {
    writeText('BUILD_NUMBER', `${versionInfo.buildNumber}\n`)
  }
  writeText('VERSION', `${version}\n`)

  console.log(`[version] synced ${version}${versionInfo.source ? ` (${versionInfo.source})` : ''}`)
}

function readVersionInfo() {
  if (existsSync(join(repoRoot, 'VERSION_BASE'))) {
    const base = readVersionBase()
    const buildInfo = readGitCommitBuildNumber()
    return {
      version: `${base}.${buildInfo.buildNumber}`,
      buildNumber: buildInfo.buildNumber,
      source: buildInfo.source,
    }
  }
  if (existsSync(join(repoRoot, 'BUILD_NUMBER'))) {
    const base = readVersionBase()
    const buildNumber = readBuildNumberSnapshot()
    return { version: `${base}.${buildNumber}`, buildNumber, source: 'BUILD_NUMBER fallback' }
  }
  return { version: readFileSync(join(repoRoot, 'VERSION'), 'utf8').trim(), buildNumber: null, source: '' }
}

function readVersionBase() {
  const base = readFileSync(join(repoRoot, 'VERSION_BASE'), 'utf8').trim()
  if (!/^\d+\.\d+$/.test(base)) {
    throw new Error(`VERSION_BASE must be major.minor, got: ${base}`)
  }
  return base
}

function readGitCommitBuildNumber() {
  const offset = readBuildNumberOffset()
  try {
    const commitCount = readGitCommitCount()
    return {
      buildNumber: offset + commitCount + (shouldUseNextCommitBuildNumber ? 1 : 0),
      source: `${shouldUseNextCommitBuildNumber ? 'next commit count' : 'git commit count'}${offset > 0 ? ` + offset ${offset}` : ''}`,
    }
  } catch {
    const fallback = readBuildNumberSnapshot()
    return {
      buildNumber: fallback + (shouldUseNextCommitBuildNumber ? 1 : 0),
      source: 'BUILD_NUMBER fallback',
    }
  }
}

function readGitCommitCount() {
  if (!hasGitHeadCommit()) {
    if (isGitWorkTree()) return 0
    throw new Error('Git HEAD is not available')
  }
  const raw = execFileSync('git', ['rev-list', '--count', 'HEAD'], {
    cwd: repoRoot,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'ignore'],
  }).trim()
  if (!/^\d+$/.test(raw)) {
    throw new Error(`git rev-list returned a non-numeric commit count: ${raw}`)
  }
  return Number(raw)
}

function hasGitHeadCommit() {
  try {
    execFileSync('git', ['rev-parse', '--verify', 'HEAD'], {
      cwd: repoRoot,
      stdio: ['ignore', 'ignore', 'ignore'],
    })
    return true
  } catch {
    return false
  }
}

function isGitWorkTree() {
  try {
    return execFileSync('git', ['rev-parse', '--is-inside-work-tree'], {
      cwd: repoRoot,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim() === 'true'
  } catch {
    return false
  }
}

function readBuildNumberOffset() {
  const offsetPath = join(repoRoot, 'BUILD_NUMBER_OFFSET')
  if (!existsSync(offsetPath)) return 0
  const raw = readFileSync(offsetPath, 'utf8').trim()
  if (!/^\d+$/.test(raw)) {
    throw new Error(`BUILD_NUMBER_OFFSET must be a non-negative integer, got: ${raw}`)
  }
  return Number(raw)
}

function readBuildNumberSnapshot() {
  const raw = readFileSync(join(repoRoot, 'BUILD_NUMBER'), 'utf8').trim()
  if (!/^\d+$/.test(raw)) {
    throw new Error(`BUILD_NUMBER must be a non-negative integer, got: ${raw}`)
  }
  return Number(raw)
}

function validateSemverLikeVersion(version, sourceName) {
  if (!/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(version)) {
    throw new Error(`${sourceName} must be a semver-like string, got: ${version}`)
  }
}

async function acquireLock() {
  mkdirSync(dirname(lockDirectory), { recursive: true })
  const start = Date.now()
  while (true) {
    try {
      mkdirSync(lockDirectory)
      return
    } catch (error) {
      if (error?.code !== 'EEXIST') throw error
      if (isStaleLock()) {
        rmSync(lockDirectory, { recursive: true, force: true })
        continue
      }
      if (Date.now() - start > lockTimeoutMs) {
        throw new Error('Timed out waiting for version sync lock')
      }
      await sleep(50)
    }
  }
}

function isStaleLock() {
  if (!existsSync(lockDirectory)) return false
  try {
    return Date.now() - statSync(lockDirectory).mtimeMs > staleLockMs
  } catch {
    return false
  }
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms))
}

function readJson(relativePath) {
  return JSON.parse(readFileSync(join(repoRoot, relativePath), 'utf8'))
}

function writeJson(relativePath, value) {
  writeText(relativePath, `${JSON.stringify(value, null, 2)}\n`)
}

function writeText(relativePath, content) {
  const targetPath = join(repoRoot, relativePath)
  const temporaryPath = `${targetPath}.${process.pid}.${writeCounter}.tmp`
  writeCounter += 1
  writeFileSync(temporaryPath, content)
  renameWithRetry(temporaryPath, targetPath)
}

function renameWithRetry(sourcePath, targetPath) {
  const maxAttempts = 20
  for (let attempt = 0; attempt < maxAttempts; attempt += 1) {
    try {
      renameSync(sourcePath, targetPath)
      return
    } catch (error) {
      if (!isRetryableRenameError(error) || attempt === maxAttempts - 1) throw error
      sleepSync(25 + attempt * 25)
    }
  }
}

function isRetryableRenameError(error) {
  return error?.code === 'EPERM' || error?.code === 'EACCES' || error?.code === 'EBUSY'
}

function sleepSync(ms) {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms)
}

function updateTomlPackageVersion(content, version) {
  const lines = content.split(/\r?\n/)
  let inPackage = false
  let updated = false
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index]
    if (/^\[package\]\s*$/.test(line)) {
      inPackage = true
      continue
    }
    if (inPackage && /^\[/.test(line)) break
    if (inPackage && /^version\s*=/.test(line)) {
      lines[index] = `version = "${version}"`
      updated = true
      break
    }
  }
  if (!updated) throw new Error('Could not find [package] version in Cargo.toml')
  return lines.join('\n')
}

function updateCargoLockPackageVersion(content, packageName, version) {
  const lines = content.split(/\r?\n/)
  let currentPackageName = ''
  let updated = false
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index]
    if (/^\[\[package\]\]\s*$/.test(line)) {
      currentPackageName = ''
      continue
    }
    const nameMatch = /^name\s*=\s*"([^"]+)"/.exec(line)
    if (nameMatch) {
      currentPackageName = nameMatch[1]
      continue
    }
    if (currentPackageName === packageName && /^version\s*=/.test(line)) {
      lines[index] = `version = "${version}"`
      updated = true
      break
    }
  }
  if (!updated) throw new Error(`Could not find package version in Cargo.lock: ${packageName}`)
  return lines.join('\n')
}
