export { PaperTrackEditorPopover, exportPreviousPaperTrackName, defaultExportAfterTrackForInsertAfter, overlayExportPlacementAfterTrack, deleteRegisteredCellKey, isInteractiveKeyboardTarget } from './stack-guides-paper-track'
export { HoverCellOverlay, StackGuideOverlay } from './stack-guides-overlay'
export { StackGuideSvgLayer } from './stack-guides-svg'
export type { StackGuideLabelMetrics } from './stack-guides-geometry'
export { STACK_GUIDE_MAX_LANE, OVERLAY_PAPER_TRACK_TOOLTIP_DELAY_MS, stackGuidePlacements, stackGuideLabelBottomPx, stackGuideNativeHeaderReachPx, stackGuideGapWidthPx, stackGuideLabelMetrics, estimatedLabelTextWidthPx, stackGuideSvgGeometry, stackGuideAnchorRegions } from './stack-guides-geometry'
export { stackGuideInsertTargetFromPoint, stackGuidePlacementUpdateFromPointer, stackGuidePlacementTargetFromPointer } from './stack-guides-interaction'
